###
GET http://localhost:8000/v1/user 
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoic3VsYXY1QHlhaG9vLmNvbSIsImlhdCI6MTY2MzU1MDA5OCwiZXhwIjoxNjYzNTUwOTk4fQ.XzvUNzqsNDD14_TENmphidP8cV_-H85OlOwZNPqkR6Q

###
POST http://localhost:8000/v1/user
Content-Type: application/json

{
    "name":"Sulav",
    "company":"XYZ Company",
    "address":"sdsadda",
    "phone":123456789,
    "email":"sulav6@yahoo.com",
    "password":"123456"
}

###
POST http://localhost:8000/v1/user/login
Content-Type: application/json

{
    "email":"sulav5@yahoo.com",
    "password":"1234567"
}

###
POST http://localhost:8000/v1/user/reset-password
Content-Type: application/json

{
    "email":"sulav5@yahoo.com"
}

###
PATCH http://localhost:8000/v1/user/reset-password
Content-Type: application/json

{
    "email":"sulav5@yahoo.com",
    "password":"1234567",
    "otp":"263496"
}

###
GET http://localhost:8000/v1/tokens
Authorization: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoic3VsYXY1QHlhaG9vLmNvbSIsImlhdCI6MTY2MzU1MTc1MSwiZXhwIjoxNjY2MTQzNzUxfQ.SxxMT6Lfc1CVvypOi1IT_Sp4tkbOEAon5rpmjMQbWW4


############# Tickets #################

###
POST http://localhost:8000/v1/ticket
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoic3VsYXY1QHlhaG9vLmNvbSIsImlhdCI6MTY2MzcyMjc0NywiZXhwIjoxNjYzNzIzNjQ3fQ.yPCkElgxI_sgohtasJGB4_I1hz6HiSBHt3kiHx82l6Y

{
    "subject":"Hello",
    "sender":"Mate",
    "message":"The form you submitted isnot working, try again later"
}

###
GET http://localhost:8000/v1/ticket/632923a2a3ded7dd62001d4b
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoic3VsYXY1QHlhaG9vLmNvbSIsImlhdCI6MTY2MzY0NDYzNSwiZXhwIjoxNjYzNjQ1NTM1fQ.gwjX82Z-7rBj5DoFNo1ZgyW0PQW3WnipIK114I0fWuI

###
PUT http://localhost:8000/v1/ticket/632923a2a3ded7dd62001d4b
Content-Type: application/json
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoic3VsYXY1QHlhaG9vLmNvbSIsImlhdCI6MTY2MzY0NDYzNSwiZXhwIjoxNjYzNjQ1NTM1fQ.gwjX82Z-7rBj5DoFNo1ZgyW0PQW3WnipIK114I0fWuI

{
    "sender":"Michael",
    "message":"This is taking way too long mate !"
}

###
PATCH http://localhost:8000/v1/ticket/632923a2a3ded7dd62001d4b
Authorization:eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJwYXlsb2FkIjoic3VsYXY1QHlhaG9vLmNvbSIsImlhdCI6MTY2MzY0NzU3MywiZXhwIjoxNjYzNjQ4NDczfQ.oZOJqkWwHryrANinh348i3APikc-LOKdwy6gLJ7PDmw


